// Generated from resources/manifest.json. Run npm run assets:sync after editing the manifest.
export const assets = [
  'assets/menu/house.png',
  'assets/menu/tree_long.png',
  'assets/menu/tree_pine.png',
  'assets/menu/bush.png',
  'assets/menu/fence.png',
  'assets/menu/cloud.png',
  'assets/menu/smoke.png',
  'assets/menu/moon.png',
  'assets/menu/power.svg',
  'assets/menu/beacon.svg',
  'assets/menu/panel_brown.png',
  'assets/menu/panel_grey.png',
  'assets/fonts/marmelad-cyrillic.woff2',
  'assets/fonts/marmelad-latin.woff2',
  'assets/audio/click-a.ogg',
  'assets/audio/tap-a.ogg',
  'assets/audio/switch-a.ogg',
  'assets/menu/setting-on.png',
  'assets/menu/setting-off.png',
  'assets/menu/level-complete.png',
  'assets/menu/setting-teal.svg',
  'assets/ui/cursor-hand.svg',
  'assets/ui/cursor-hand-active.svg',
  'assets/menu/close.png',
  'assets/fonts/kenney-future-narrow.ttf',
  'assets/menu/star-filled.png',
  'assets/menu/star-empty.png',
  'assets/menu/arrow-left.png',
  'assets/menu/arrow-right.png',
  'assets/menu/spark.png',
  'assets/audio/electric-soft.mp3',
  'assets/menu/dialog-action.png',
] as const;
